The News Week home page clone merge request
temesghentekeste/newsweek-clone pull request #3
Opened 2020-05-07 16:40 UTC by temesghentekeste

I created a branch called "homepage" and developed that branch.

 On the initial commit, I created a basic structure for the page and added CDN links to Bootstrap, JQuery, Fontawesome, and Google Fonts.

 "Mobile first" approach is used in order to achieve responsiveness principles.

 Elements are positioned using Bootstrap and a custom CSS style.

Please review my project before I merge my branch.

Thanks in advance!

2020-05-08 12:22 UTC, santiago-rodrig commented
## Pull Request under review by @santiago-rodrig (TSE)

2020-05-08 12:41 UTC, santiago-dev96 requested changes
# Changes required! :no_entry_sign:

On small mobiles (~360 widths), the sign-in link doesn't display properly.

![image](https://user-images.githubusercontent.com/43162770/81406382-73b10100-9107-11ea-8dd7-070f3544341e.png)

Please go ahead and implement the changes I requested. We are no assessing JavaScript for HTML & CSS projects, keep that in mind in the future. Have a nice day :wave:!

You can find me in slack as **srodrig**.

2020-05-08 12:41 UTC, santiago-rodrig commented on README.md
> +- VS Code
The text editor is not important

2020-05-08 12:41 UTC, santiago-rodrig commented on README.md
> +- Firefox Developer Edition dev tools
Neither the browser tools

2020-05-08 12:41 UTC, santiago-rodrig commented on css/custom.css
> +}
Great use of CSS variables!

2020-05-08 12:41 UTC, santiago-rodrig commented on js/scripts.js
> +    console.log($logoContainer)
Don't push console logs

2020-05-08 12:41 UTC, santiago-rodrig commented on js/scripts.js
> +    // }
Don't push commented code

2020-05-08 14:21 UTC, temesghentekeste commented
Thanks, @santiago-rodrig for your review and I have fixed them all as per your suggestions.

2020-05-09 09:25 UTC, sumancrest0001 approved these changes
**Congratulation @temesghentekeste :clap:  :clap:** 
You have done a terrific job and it looks similar to the original site. It's a YES from my side. You can merge the PR and submit the project completion form. 
[OPTIONAL] Try to avoid !important in your stylesheet. It is not a good practice. 

**HAPPY CODING !!!**
![mission](https://user-images.githubusercontent.com/37747619/81469859-21efa000-9207-11ea-82b8-7b3f4a74f2f9.gif)

2020-05-09 10:54 UTC, temesghentekeste commented
Thanks, @sumancrest0001 for approving the project and I will try to apply your recommendation in my next project.

2020-05-09 10:55 UTC, merged